const data = [
    {
        name: "Bartosz Ciechanowski",
        url: "https://ciechanow.ski",
        img: "bar.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding", "bartosz"],
    },
    {
        name: "Radio Garden",
        url: "https://radio.garden",
        img: "rdg.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world", "radio", "garden"],
    },
    {
        name: "Unequal Scenes",
        url: "https://unequalscenes.com",
        img: "uqs.jpg",
        icon: ["art"],
        keywords: ["art", "unequal", "scenes", "photo"],
    },
    {
        name: "Radar Tutorial",
        url: "https://radartutorial.eu/index.fr.html",
        img: "rad.jpg",
        icon: ["radar"],
        keywords: ["learn", "radar", "tutorial", "science"],
    },
    {
        name: "The Size Of Space",
        url: "https://neal.fun/size-of-space/",
        img: "tss.jpg",
        icon: ["space"],
        keywords: ["learn", "fun", "space", "size", "neal"],
    },
    {
        name: "Infinite Flowers",
        url: "https://infiniteflowers.net",
        img: "ifl.jpg",
        icon: ["art"],
        keywords: ["art", "flowers", "infinite", "zoom"],
    },
    {
        name: "Villemin Gérard",
        url: "http://villemin.gerard.free.fr",
        img: "gvl.jpg",
        icon: ["maths"],
        keywords: ["learn", "maths", "villemin", "gerard"],
    },
    {
        name: "Worldometers",
        url: "https://worldometers.info",
        img: "wdm.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world"],
    },
    {
        name: "Zombo.com",
        url: "https://zombo.com",
        img: "zco.jpg",
        icon: ["art"],
        keywords: ["fun", "zombo", "com"],
    },
    {
        name: "L'Avionnaire",
        url: "https://lavionnaire.fr",
        img: "avn.jpg",
        icon: ["aviation"],
        keywords: ["learn", "aviation", "avionnaire"],
    },
    {
        name: "Nareva",
        url: "http://nareva.info/portail_nareva.htm",
        img: "nar.jpg",
        icon: ["various"],
        keywords: ["learn", "various", "nareva"],
    },
    {
        name: "Road Numbering Systems",
        url: "https://sites.google.com/site/roadnumberingsystems",
        img: "rns.jpg",
        icon: ["wdata"],
        keywords: ["learn", "wdata", "road"],
    },
    {
        name: "Just for Fun",
        url: "https://justforfun.io",
        img: "jff.jpg",
        icon: ["art"],
        keywords: ["fun", "art", "just", "neal"],
    },
    {
        name: "Neal.fun",
        url: "https://neal.fun",
        img: "nea.jpg",
        icon: ["various"],
        keywords: ["fun", "various", "neal"],
    },
    {
        name: "The Deep Sea",
        url: "https://neal.fun/deep-sea",
        img: "tds.jpg",
        icon: ["sea"],
        keywords: ["learn", "fun", "sea", "deep", "neal"],
    },
    {
        name: "Space Elevator",
        url: "https://neal.fun/space-elevator/",
        img: "sel.jpg",
        icon: ["space"],
        keywords: ["learn", "fun", "space", "elevator", "neal"],
    },
    {
        name: "BeepBox",
        url: "https://beepbox.co",
        img: "bbx.jpg",
        icon: ["music"],
        keywords: ["learn", "music", "beepbox"],
    },
    {
        name: "973-eht-namuh-973",
        url: "https://973-eht-namuh-973.com",
        img: "973.jpg",
        icon: ["artu", "photowarning"],
        keywords: ["art", "universe", "weird", "eht", "namuh", "973"],
    },
    {
        name: "Red Blob Games",
        url: "https://redblobgames.com",
        img: "rbg.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding", "red", "blob"],
    },
    {
        name: "Jodi",
        url: "https://jodi.org",
        img: "jod.jpg",
        icon: ["artu", "photowarning"],
        keywords: ["art", "universe", "weird", "jodi"],
    },
    {
        name: "Superbad",
        url: "https://superbad.com",
        img: "spb.jpg",
        icon: ["artu", "photowarning"],
        keywords: ["art", "unvierse", "weird", "superbad"],
    },
    {
        name: "Windows93",
        url: "https://windows93.net",
        img: "w93.jpg",
        icon: ["artu", "photowarning"],
        keywords: ["art", "universe", "weird", "windows", "93"],
    },
    {
        name: "Grepolis",
        url: "https://grepolis.com",
        img: "gre.jpg",
        icon: ["games"],
        keywords: ["fun", "games", "grepolis"],
    },
    {
        name: "Excalidraw",
        url: "https://excalidraw.com",
        img: "exc.jpg",
        icon: ["tool"],
        keywords: ["learn", "fun", "tool", "excalidraw"],
    },
    {
        name: "Encyclopédie Des Armes",
        url: "https://encyclopedie-des-armes.com",
        img: "eda.jpg",
        icon: ["military"],
        keywords: ["learn", "military", "weapons", "armes"],
    },
    {
        name: "Map Army",
        url: "https://map.army",
        img: "mmp.jpg",
        icon: ["military"],
        keywords: ["learn", "map", "military", "army"],
    },
    {
        name: "Tourdumondiste",
        url: "https://tourdumondiste.com",
        img: "tdm.jpg",
        icon: ["travel"],
        keywords: ["fun", "tour", "world", "monde", "travel", "voyage"],
    },
    {
        name: "NaNoWriMo",
        url: "https://nanowrimo.org",
        img: "nnw.jpg",
        icon: ["writing"],
        keywords: ["fun", "writing", "nano", "nanowrimo"],
    },
    {
        name: "Simone's Computer",
        url: "https://simone.computer/#/webdesktops",
        img: "sim.jpg",
        icon: ["artu", "photowarning"],
        keywords: ["fun", "universe", "weird", "simone", "computer"],
    },
    {
        name: "Ventusky",
        url: "https://ventusky.com",
        img: "vts.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "ventusky", "weather", "map", "world"],
    },
    {
        name: "Submarine Cable Map",
        url: "https://submarinecablemap.com",
        img: "scm.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "submarine", "network", "cable", "map", "world", "web"],
    },
    {
        name: "Marine Traffic",
        url: "https://marinetraffic.com",
        img: "mrt.jpg",
        icon: ["ship"],
        keywords: ["fun", "ship", "sailing", "marine", "traffic", "map", "world"],
    },
    {
        name: "Plane Finder",
        url: "https://planefinder.net",
        img: "plf.jpg",
        icon: ["aviation"],
        keywords: ["fun", "aviation", "map", "traffic", "plane", "world"],
    },
    {
        name: "The Atlas of Economic Complexity",
        url: "https://atlas.cid.harvard.edu/explore",
        img: "aec.jpg",
        icon: ["wdata"],
        keywords: ["learn", "atlas", "wdata", "economic", "world"],
    },
    {
        name: "Robokill 2<br>Leviathan Five",
        url: "https://silvergames.com/fr/robokill-2",
        img: "rbk.jpg",
        icon: ["games"],
        keywords: ["fun", "games", "robokill"],
    },
    {
        name: "Cyberthreat Live map",
        url: "https://cybermap.kaspersky.com",
        img: "clm.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world", "map", "cyber", "threat", "live", "network", "web"],
    },
    {
        name: "Paper Toilet",
        url: "https://papertoilet.com",
        img: "ppt.jpg",
        icon: ["art"],
        keywords: ["fun", "paper", "toilet"],
    },
    {
        name: "The Useless Web",
        url: "https://theuselessweb.com",
        img: "usw.jpg",
        icon: ["various"],
        keywords: ["fun", "useless", "web", "various"],
    },
    {
        name: "Optical Toys",
        url: "https://optical.toys",
        img: "opt.jpg",
        icon: ["science"],
        keywords: ["learn", "fun", "optical", "toys", "science", "ilusions"],
    },
    {
        name: "The Zoomquilt",
        url: "https://zoomquilt.org",
        img: "zql.jpg",
        icon: ["art"],
        keywords: ["art", "zoomquilt", "infinite", "zoom"],
    },
    {
        name: "Hydromeda",
        url: "https://hydromeda.org",
        img: "hyd.jpg",
        icon: ["art"],
        keywords: ["art", "hydromeda", "infinite", "zoom"],
    },
    {
        name: "Pointer Pointer",
        url: "https://pointerpointer.com",
        img: "ptr.jpg",
        icon: ["art"],
        keywords: ["fun", "pointer", "photo"],
    },
    {
        name: "Staggering Beauty",
        url: "http://staggeringbeauty.com",
        img: "stg.jpg",
        icon: ["art", "photowarning"],
        keywords: ["fun", "beauty", "staggering"],
    },
    {
        name: "Patience is a virtue",
        url: "http://www.patience-is-a-virtue.org",
        img: "pat.jpg",
        icon: ["games"],
        keywords: ["fun", "games", "patience", "virtue"],
    },
    {
        name: "Cisco Binary Game",
        url: "https://learningcontent.cisco.com/games/binary/index.html",
        img: "cbg.png",
        icon: ["games"],
        keywords: ["learn", "fun", "games", "cisco", "binary"],
    },
    {
        name: "Find the Invisible Cow",
        url: "https://findtheinvisiblecow.com",
        img: "cow.jpg",
        icon: ["games"],
        keywords: ["fun", "games", "find", "invisible", "cow"],
    },
    {
        name: "The Nicest Place on the Internet",
        url: "https://thenicestplace.net",
        img: "nic.jpg",
        icon: ["art"],
        keywords: ["fun", "nicest", "place", "web", "video"],
    },
    {
        name: "Click Click Click",
        url: "https://clickclickclick.click",
        img: "cli.jpg",
        icon: ["games"],
        keywords: ["fun", "games", "click"],
    },
    {
        name: "Blue Ball Machine",
        url: "https://theuselessweb.site/blueballmachine",
        img: "bbm.jpg",
        icon: ["art"],
        keywords: ["art", "blue", "ball", "machine"],
    },
    {
        name: "Dernière Page d'Internet",
        url: "https://dernierepage.com",
        img: "dpi.jpg",
        icon: ["art"],
        keywords: ["fun", "web", "page", "last", "internet", "derniere"],
    },
    {
        name: "Stuff in Space",
        url: "https://stuffin.space",
        img: "sis.jpg",
        icon: ["space"],
        keywords: ["fun", "stuff", "space"],
    },
    {
        name: "Nasa Asteroid Watch",
        url: "https://eyes.nasa.gov/apps/asteroids/#/watch/2024_wn4",
        img: "naw.jpg",
        icon: ["space"],
        keywords: ["fun", "nasa", "asteroid", "space"],
    },
    {
        name: "Pleine-Peau.com",
        url: "https://pleine-peau.com",
        img: "ppc.jpg",
        icon: ["art", "photowarning", "nsfw"],
        keywords: ["art", "pleine", "peau", "nsfw"],
    },
    {
        name: "Oxide.org",
        url: "http://oxide.org",
        img: "oxi.jpg",
        icon: ["art"],
        keywords: ["art", "oxide"],
    },
    {
        name: "Jeff Thompson",
        url: "https://jeffreythompson.org/",
        img: "jft.jpg",
        icon: ["art"],
        keywords: ["art", "jeff", "thompson"],
    },
    {
        name: "Collision Detection",
        url: "https://jeffreythompson.org/collision-detection/index.php",
        img: "col.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding", "collision", "detection"],
    },
    {
        name: "Learn OpenGL",
        url: "https://learnopengl.com/",
        img: "ope.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding", "opengl"],
    },
    {
        name: "Learn X in Y minutes",
        url: "https://learnxinyminutes.com/",
        img: "xiy.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding"],
    },
    {
        name: "e-PG Pathshala",
        url: "https://epgp.inflibnet.ac.in/Home",
        img: "epg.jpg",
        icon: ["various"],
        keywords: ["learn", "various", "pathshala"],
    },
    {
        name: "Project Euler",
        url: "https://projecteuler.net",
        img: "pel.jpg",
        icon: ["coding"],
        keywords: ["learn", "project", "coding", "euler"],
    },
    {
        name: "Internet Archive",
        url: "https://archive.org",
        img: "arc.jpg",
        icon: ["tool"],
        keywords: ["fun", "tool", "internet", "web", "archive"],
    },
    {
        name: "PolitiScales",
        url: "https://politiscales.fr/",
        img: "pol.jpg",
        icon: ["games"],
        keywords: ["fun", "politic", "scale", "games"],
    },
    {
        name: "OSDev.org",
        url: "https://wiki.osdev.org",
        img: "osd.jpg",
        icon: ["coding"],
        keywords: ["learn", "coding", "os", "dev"],
    },
    {
        name: "dCode",
        url: "https://dcode.fr",
        img: "dco.jpg",
        icon: ["maths"],
        keywords: ["learn", "fun", "maths", "dcode", "code"],
    },
    {
        name: "OpenStreetMap",
        url: "https://openstreetmap.org",
        img: "osm.jpg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "map", "open", "street"],
    },
    {
        name: "Esolangs",
        url: "https://esolangs.org",
        img: "esl.jpg",
        icon: ["coding"],
        keywords: ["learn", "fun", "coding", "esolangs", "languages"],
    },
    {
        name: "Mathcurve",
        url: "https://mathcurve.com",
        img: "mtc.jpg",
        icon: ["maths"],
        keywords: ["learn", "maths", "curves"],
    },
    {
        name: "Matematica.pt",
        url: "https://matematica.pt/en/index.php",
        img: "mpt.jpg",
        icon: ["maths"],
        keywords: ["learn", "maths"],
    },
    {
        name: "OEIS",
        url: "https://oeis.org",
        img: "oei.jpg",
        icon: ["maths"],
        keywords: ["learn", "maths", "oeis"],
    },
    {
        name: "Ultimate Medicine Quiz",
        url: "https://kodpe.github.io/umq/html/quizz.html",
        img: "umq.jpg",
        icon: ["games"],
        keywords: ["learn", "fun", "games", "ultimate", "medicine", "quiz"],
    },
    {
        name: "Tutoriel Synthétiseur",
        url: "https://learningsynths.ableton.com/fr/get-started",
        img: "syn.jpg",
        icon: ["music"],
        keywords: ["learn", "fun", "tutorial", "music", "synth"],
    },
    {
        name: "The First Website",
        url: "https://info.cern.ch/hypertext/WWW/TheProject.html",
        img: "www.jpg",
        icon: ["art"],
        keywords: ["fun", "first", "premier", "web", "internet"],
    },
    {
        name: "Dessin et Géométrie variable",
        url: "https://dessingeometri.wordpress.com",
        img: "dgv.jpg",
        icon: ["art"],
        keywords: ["maths", "art", "draw", "geometry"],
    },
    {
        name: "Symbl",
        url: "SYMBL",
        img: "sym.jpg",
        icon: ["tool"],
        keywords: ["fun", "tool", "emoji", "symbl"],
    },
    {
        name: "Generative Artistry Tutorials",
        url: "https://generativeartistry.com/tutorials",
        img: "gna.jpg",
        icon: ["coding"],
        keywords: ["art", "tool", "coding", "generative", "tutorials"],
    },
    {
        name: "1018 Homepage Design Examples",
        url: "https://baymard.com/homepage-and-category-usability/benchmark/page-types/homepage",
        img: "hde.jpg",
        icon: ["coding"],
        keywords: ["coding", "design", "learn", "web"],
    },
    {
        name: "Devhints.io Rico's cheatsheets",
        url: "https://devhints.io/",
        img: "ric.jpg",
        icon: ["coding"],
        keywords: ["coding", "learn"],
    },
    {
        name: "The Million Dollar Homepage",
        url: "http://milliondollarhomepage.com",
        img: "mdp.jpg",
        icon: ["art", "nsfw"],
        keywords: ["fun", "weird", "web"],
    },
    {
        name: "Aesthetics Wiki",
        url: "https://aesthetics.fandom.com/wiki/List_of_Aesthetics",
        img: "aew.jpg",
        icon: ["art"],
        keywords: ["learn", "web", "wiki", "art"],
    },
    {
        name: "The Periodic Table of Storytelling",
        url: "https://jamesharris.design/periodic",
        img: "pts.jpg",
        icon: ["writing"],
        keywords: ["learn", "writing"],
    },
    {
        name: "Fractal Machine",
        url: "https://sciencevsmagic.net/fractal",
        img: "fra.jpg",
        icon: ["maths"],
        keywords: ["art", "games", "maths", "geometry", "fractals"],
    },
    {
        name: "Logic Grid",
        url: "https://sciencevsmagic.net/logicgrid",
        img: "log.jpg",
        icon: ["maths"],
        keywords: ["art", "maths", "geometry", "fractals", "grid"],
    },
    {
        name: "Tv Tropes",
        url: "https://tvtropes.org/pmwiki/pmwiki.php/Main/Tropes",
        img: "tvt.jpg",
        icon: ["writing"],
        keywords: ["art", "writing", "book", "wiki", "learn"],
    },
    {
        name: "Inkarnate",
        url: "https://inkarnate.com",
        img: "ink.jpg",
        icon: ["tool"],
        keywords: ["writing", "map", "tool", "fun"],
    },
    {
        name: "Lifemap",
        url: "https://lifemap-ncbi.univ-lyon1.fr",
        img: "lml.jpg",
        icon: ["science"],
        keywords: ["learn", "life", "tree", "evolution", "map"],
    },
    {
        name: "Itch.io",
        url: "https://itch.io",
        img: "itc.jpg",
        icon: ["various"],
        keywords: ["fun", "games", "coding", "art"],
    },
    {
        name: "Circos Table Viewer",
        url: "https://mk.bcgsc.ca/tableviewer",
        img: "ctv.jpg",
        icon: ["science"],
        keywords: ["learn", "medicine", "genetics"],
    },
    {
        name: "2b2t Maps",
        url: "https://map.daporkchop.net/#2021_256k_isometric/0/6/96/-656/0",
        img: "b2t.jpg",
        icon: ["games"],
        keywords: ["fun", "weird", "map", "games", "web"],
    },
    {
        name: "LHC Page 1",
        url: "https://op-webtools.web.cern.ch/vistar/?usr=LHC1",
        img: "lhc.jpg",
        icon: ["science"],
        keywords: ["fun", "physics", "science"],
    },
    {
        name: "Human (GRCh38/hg38)",
        url: "https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr7%3A155799529%2D155812871&hgsid=346994980_E73Sa36VARAEPLasBPPOsvdRfbPS",
        img: "hum.jpg",
        icon: ["science"],
        keywords: ["learn", "medicine", "genetics"],
    },
    {
        name: "Science Vs Magic",
        url: "https://sciencevsmagic.net",
        img: "svm.jpg",
        icon: ["maths"],
        keywords: ["art", "maths", "geometry", "fractals", "learn"],
    },
    {
        name: "Tristan da Cunha",
        url: "https://tristandc.com/index.php",
        img: "tdc.jpg",
        icon: ["location"],
        keywords: ["learn", "location", "geography", "island", "sea"],
    },
    {
        name: "One Zoom Biota",
        url: "https://onezoom.org/linnean",
        img: "ozb.jpg",
        icon: ["science"],
        keywords: ["learn", "life", "tree", "evolution", "map"],
    },
    {
        name: "Seismic Monitor",
        url: "https://ds.iris.edu/seismon/index.phtml",
        img: "sei.jpg",
        icon: ["science"],
        keywords: ["learn", "geography", "map", "earthquake"],
    },
    {
        name: "The 2022 r/place Atlas",
        url: "https://2022.place-atlas.stefanocoding.me",
        img: "rpa.jpg",
        icon: ["art"],
        keywords: ["fun", "web", "map", "art"],
    },
    {
        name: "Hashima Island",
        url: "https://hashima-island.co.uk",
        img: "has.jpg",
        icon: ["location"],
        keywords: ["fun", "weird", "island", "location"],
    },

];
