const data = [
    {
        name: "Ultimate Kung Fu Chess",
        url: "https://nemosites.com/kfc/",
        img: "ukc",
        icon: ["games"],
        keywords: ["fun", "game", "chess", "kodp"],
    },
    {
        name: "The True Size",
        url: "https://www.thetruesize.com",
        img: "tts",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "maps", "true", "size", "countrie"],
    },
    {
        name: "Travle",
        url: "https://travle.earth",
        img: "tvl",
        icon: ["games"],
        keywords: ["fun", "game", "wdata", "maps", "countrie"],
    },
    {
        name: "Bartosz Ciechanowski",
        url: "https://ciechanow.ski",
        img: "bar",
        icon: ["coding"],
        keywords: ["learn", "coding", "bartosz"],
    },
    {
        name: "Radio Garden",
        url: "https://radio.garden",
        img: "rdg",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world", "radio", "garden"],
    },
    {
        name: "Unequal Scenes",
        url: "https://unequalscenes.com",
        img: "uqs",
        icon: ["art"],
        keywords: ["art", "unequal", "scenes", "photo"],
    },
    {
        name: "Miamoalex",
        url: "https://miamoalex.net/home",
        img: "mim",
        icon: ["various"],
        keywords: ["fun", "game", "art", "web", "food", "internet", "music", "weird"],
    },
    {
        name: "Miamo.fun",
        url: "https://miamo.fun",
        img: "mia",
        icon: ["games"],
        keywords: ["fun", "game", "web", "food", "internet"],
    },
    {
        name: "Pouler.fr",
        url: "https://pouler.fr",
        img: "plr",
        icon: ["games"],
        keywords: ["fun", "game", "web", "food", "internet"],
    },
    {
        name: "Radar Tutorial",
        url: "https://radartutorial.eu/index.fr.html",
        img: "rad",
        icon: ["radar"],
        keywords: ["learn", "radar", "tutorial", "science"],
    },
    {
        name: "The Size Of Space",
        url: "https://neal.fun/size-of-space/",
        img: "tss",
        icon: ["space"],
        keywords: ["learn", "fun", "space", "size", "neal"],
    },
    {
        name: "Infinite Flowers",
        url: "https://infiniteflowers.net",
        img: "ifl",
        icon: ["art"],
        keywords: ["art", "flowers", "infinite", "zoom"],
    },
    {
        name: "Villemin Gérard",
        url: "http://villemin.gerard.free.fr",
        img: "gvl",
        icon: ["maths"],
        keywords: ["learn", "maths", "villemin", "gerard"],
    },
    {
        name: "Worldometers",
        url: "https://worldometers.info",
        img: "wdm",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world"],
    },
    {
        name: "Zombo.com",
        url: "https://zombo.com",
        img: "zco",
        icon: ["art"],
        keywords: ["fun", "zombo", "com"],
    },
    {
        name: "L'Avionnaire",
        url: "https://lavionnaire.fr",
        img: "avn",
        icon: ["aviation"],
        keywords: ["learn", "aviation", "avionnaire"],
    },
    {
        name: "Nareva",
        url: "http://nareva.info/portail_nareva.htm",
        img: "nar",
        icon: ["various"],
        keywords: ["learn", "various", "nareva"],
    },
    {
        name: "Road Numbering Systems",
        url: "https://sites.google.com/site/roadnumberingsystems",
        img: "rns",
        icon: ["wdata"],
        keywords: ["learn", "wdata", "road"],
    },
    {
        name: "Just for Fun",
        url: "https://justforfun.io",
        img: "jff",
        icon: ["art"],
        keywords: ["fun", "art", "just", "neal"],
    },
    {
        name: "Neal.fun",
        url: "https://neal.fun",
        img: "nea",
        icon: ["various"],
        keywords: ["fun", "various", "neal"],
    },
    {
        name: "The Deep Sea",
        url: "https://neal.fun/deep-sea",
        img: "tds",
        icon: ["sea"],
        keywords: ["learn", "fun", "sea", "deep", "neal"],
    },
    {
        name: "Space Elevator",
        url: "https://neal.fun/space-elevator/",
        img: "sel",
        icon: ["space"],
        keywords: ["learn", "fun", "space", "elevator", "neal"],
    },
    {
        name: "BeepBox",
        url: "https://beepbox.co",
        img: "bbx",
        icon: ["music"],
        keywords: ["learn", "music", "beepbox"],
    },
    {
        name: "973-eht-namuh-973",
        url: "https://973-eht-namuh-973.com",
        img: "973",
        icon: ["artu"],
        keywords: ["art", "universe", "weird", "eht", "namuh", "973"],
    },
    {
        name: "Red Blob Games",
        url: "https://redblobgames.com",
        img: "rbg",
        icon: ["coding"],
        keywords: ["learn", "coding", "red", "blob"],
    },
    {
        name: "Jodi",
        url: "https://jodi.org",
        img: "jod",
        icon: ["artu", "photowarning"],
        keywords: ["art", "universe", "weird", "jodi"],
    },
    {
        name: "Superbad",
        url: "https://superbad.com",
        img: "spb",
        icon: ["artu", "photowarning"],
        keywords: ["art", "unvierse", "weird", "superbad"],
    },
    {
        name: "Windows93",
        url: "https://windows93.net",
        img: "w93",
        icon: ["artu", "photowarning"],
        keywords: ["art", "universe", "weird", "windows", "93"],
    },
    {
        name: "Grepolis",
        url: "https://grepolis.com",
        img: "gre",
        icon: ["games"],
        keywords: ["fun", "games", "grepolis"],
    },
    {
        name: "Excalidraw",
        url: "https://excalidraw.com",
        img: "exc",
        icon: ["tool"],
        keywords: ["learn", "fun", "tool", "excalidraw"],
    },
    {
        name: "Encyclopédie Des Armes",
        url: "https://encyclopedie-des-armes.com",
        img: "eda",
        icon: ["military"],
        keywords: ["learn", "military", "weapons", "armes"],
    },
    {
        name: "Map Army",
        url: "https://www.map.army",
        img: "mmp",
        icon: ["military"],
        keywords: ["learn", "maps", "military", "army"],
    },
    {
        name: "Tourdumondiste",
        url: "https://tourdumondiste.com",
        img: "tdm",
        icon: ["travel"],
        keywords: ["fun", "tour", "world", "monde", "travel", "voyage"],
    },
    {
        name: "Kung Fu Chess",
        url: "https://www.kfchess.com",
        img: "kfc",
        icon: ["games"],
        keywords: ["fun", "game", "chess"],
    },
    {
        name: "NaNoWriMo",
        url: "https://nanowrimo.org",
        img: "nnw",
        icon: ["writing"],
        keywords: ["fun", "writing", "nano", "nanowrimo"],
    },
    {
        name: "Simone's Computer",
        url: "https://simone.computer/#/webdesktops",
        img: "sim",
        icon: ["artu", "photowarning"],
        keywords: ["fun", "universe", "weird", "simone", "computer"],
    },
    {
        name: "Ventusky",
        url: "https://ventusky.com",
        img: "vts",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "ventusky", "weather", "maps", "world"],
    },
    {
        name: "Submarine Cable Map",
        url: "https://submarinecablemap.com",
        img: "scm",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "submarine", "network", "cable", "maps", "world", "web"],
    },
    {
        name: "Marine Traffic",
        url: "https://marinetraffic.com",
        img: "mrt",
        icon: ["ship"],
        keywords: ["fun", "ship", "sailing", "marine", "traffic", "maps", "world"],
    },
    {
        name: "Plane Finder",
        url: "https://planefinder.net",
        img: "plf",
        icon: ["aviation"],
        keywords: ["fun", "aviation", "maps", "traffic", "plane", "world"],
    },
    {
        name: "The Atlas of Economic Complexity",
        url: "https://atlas.cid.harvard.edu/explore",
        img: "aec",
        icon: ["wdata"],
        keywords: ["learn", "atlas", "wdata", "economic", "world"],
    },
    {
        name: "Robokill 2<br>Leviathan Five",
        url: "https://silvergames.com/fr/robokill-2",
        img: "rbk",
        icon: ["games"],
        keywords: ["fun", "games", "robokill"],
    },
    {
        name: "Cyberthreat Live map",
        url: "https://cybermap.kaspersky.com",
        img: "clm",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "world", "maps", "cyber", "threat", "live", "network", "web"],
    },
    {
        name: "Paper Toilet",
        url: "https://papertoilet.com",
        img: "ppt",
        icon: ["art"],
        keywords: ["fun", "paper", "toilet"],
    },
    {
        name: "The Useless Web",
        url: "https://theuselessweb.com",
        img: "usw",
        icon: ["various"],
        keywords: ["fun", "useless", "web", "various"],
    },
    {
        name: "Optical Toys",
        url: "https://optical.toys",
        img: "opt",
        icon: ["science"],
        keywords: ["learn", "fun", "optical", "toys", "science", "ilusions"],
    },
    {
        name: "The Zoomquilt",
        url: "https://zoomquilt.org",
        img: "zql",
        icon: ["art"],
        keywords: ["art", "zoomquilt", "infinite", "zoom"],
    },
    {
        name: "Hydromeda",
        url: "https://hydromeda.org",
        img: "hyd",
        icon: ["art"],
        keywords: ["art", "hydromeda", "infinite", "zoom"],
    },
    {
        name: "Pointer Pointer",
        url: "https://pointerpointer.com",
        img: "ptr",
        icon: ["art"],
        keywords: ["fun", "pointer", "photo"],
    },
    {
        name: "Staggering Beauty",
        url: "http://staggeringbeauty.com",
        img: "stg",
        icon: ["art", "photowarning"],
        keywords: ["fun", "beauty", "staggering"],
    },
    {
        name: "Patience is a virtue",
        url: "http://www.patience-is-a-virtue.org",
        img: "pat",
        icon: ["games"],
        keywords: ["fun", "games", "patience", "virtue"],
    },
    {
        name: "Cisco Binary Game",
        url: "https://learningcontent.cisco.com/games/binary/index.html",
        img: "cbg",
        icon: ["games"],
        keywords: ["learn", "fun", "games", "cisco", "binary"],
    },
    {
        name: "Find the Invisible Cow",
        url: "https://findtheinvisiblecow.com",
        img: "cow",
        icon: ["games"],
        keywords: ["fun", "games", "find", "invisible", "cow"],
    },
    {
        name: "The Nicest Place on the Internet",
        url: "https://thenicestplace.net",
        img: "nic",
        icon: ["art"],
        keywords: ["fun", "nicest", "place", "web", "video"],
    },
    {
        name: "Click Click Click",
        url: "https://clickclickclick.click",
        img: "cli",
        icon: ["games"],
        keywords: ["fun", "games", "click"],
    },
    {
        name: "Blue Ball Machine",
        url: "https://theuselessweb.site/blueballmachine",
        img: "bbm",
        icon: ["art"],
        keywords: ["art", "blue", "ball", "machine"],
    },
    {
        name: "Dernière Page d'Internet",
        url: "https://dernierepage.com",
        img: "dpi",
        icon: ["art"],
        keywords: ["fun", "web", "page", "last", "internet", "derniere"],
    },
    {
        name: "Stuff in Space",
        url: "https://stuffin.space",
        img: "sis",
        icon: ["space"],
        keywords: ["fun", "stuff", "space"],
    },
    {
        name: "Nasa Asteroid Watch",
        url: "https://eyes.nasa.gov/apps/asteroids/#/watch/2024_wn4",
        img: "naw",
        icon: ["space"],
        keywords: ["fun", "nasa", "asteroid", "space"],
    },
    {
        name: "Oxide.org",
        url: "http://oxide.org",
        img: "oxi",
        icon: ["art"],
        keywords: ["art", "oxide"],
    },
    {
        name: "Jeff Thompson",
        url: "https://jeffreythompson.org/",
        img: "jft",
        icon: ["art"],
        keywords: ["art", "jeff", "thompson"],
    },
    {
        name: "Collision Detection",
        url: "https://jeffreythompson.org/collision-detection/index.php",
        img: "col",
        icon: ["coding"],
        keywords: ["learn", "coding", "collision", "detection"],
    },
    {
        name: "Learn OpenGL",
        url: "https://learnopengl.com/",
        img: "ope",
        icon: ["coding"],
        keywords: ["learn", "coding", "opengl"],
    },
    {
        name: "Learn X in Y minutes",
        url: "https://learnxinyminutes.com/",
        img: "xiy",
        icon: ["coding"],
        keywords: ["learn", "coding"],
    },
    {
        name: "e-PG Pathshala",
        url: "https://epgp.inflibnet.ac.in/Home",
        img: "epg",
        icon: ["various"],
        keywords: ["learn", "various", "pathshala"],
    },
    {
        name: "Project Euler",
        url: "https://projecteuler.net",
        img: "pel",
        icon: ["coding"],
        keywords: ["learn", "project", "coding", "euler"],
    },
    {
        name: "Internet Archive",
        url: "https://archive.org",
        img: "arc",
        icon: ["tool"],
        keywords: ["fun", "tool", "internet", "web", "archive"],
    },
    {
        name: "PolitiScales",
        url: "https://politiscales.fr/",
        img: "pol",
        icon: ["games"],
        keywords: ["fun", "politic", "scale", "games"],
    },
    {
        name: "OSDev.org",
        url: "https://wiki.osdev.org",
        img: "osd",
        icon: ["coding"],
        keywords: ["learn", "coding", "os", "dev"],
    },
    {
        name: "dCode",
        url: "https://dcode.fr",
        img: "dco",
        icon: ["maths"],
        keywords: ["learn", "fun", "maths", "dcode", "code"],
    },
    {
        name: "OpenStreetMap",
        url: "https://openstreetmap.org",
        img: "osm",
        icon: ["wdata"],
        keywords: ["fun", "wdata", "maps", "open", "street"],
    },
    {
        name: "Esolangs",
        url: "https://esolangs.org",
        img: "esl",
        icon: ["coding"],
        keywords: ["learn", "fun", "coding", "esolangs", "languages"],
    },
    {
        name: "Mathcurve",
        url: "https://mathcurve.com",
        img: "mtc",
        icon: ["maths"],
        keywords: ["learn", "maths", "curves"],
    },
    {
        name: "Matematica.pt",
        url: "https://matematica.pt/en/index.php",
        img: "mpt",
        icon: ["maths"],
        keywords: ["learn", "maths"],
    },
    {
        name: "OEIS",
        url: "https://oeis.org",
        img: "oei",
        icon: ["maths"],
        keywords: ["learn", "maths", "oeis"],
    },
    {
        name: "Ultimate Medicine Quiz",
        url: "https://kodpe.github.io/umq/html/quizz.html",
        img: "umq",
        icon: ["games"],
        keywords: ["learn", "fun", "games", "ultimate", "medicine", "quiz", "kodp"],
    },
    {
        name: "Tutoriel Synthétiseur",
        url: "https://learningsynths.ableton.com/fr/get-started",
        img: "syn",
        icon: ["music"],
        keywords: ["learn", "fun", "tutorial", "music", "synth"],
    },
    {
        name: "The First Website",
        url: "https://info.cern.ch/hypertext/WWW/TheProject.html",
        img: "www",
        icon: ["art"],
        keywords: ["fun", "first", "premier", "web", "internet"],
    },
    {
        name: "Dessin et Géométrie variable",
        url: "https://dessingeometri.wordpress.com",
        img: "dgv",
        icon: ["art"],
        keywords: ["maths", "art", "draw", "geometry"],
    },
    {
        name: "Symbl",
        url: "https://symbl.cc",
        img: "sym",
        icon: ["tool"],
        keywords: ["fun", "tool", "emoji", "symbl"],
    },
    {
        name: "Generative Artistry Tutorials",
        url: "https://generativeartistry.com/tutorials",
        img: "gna",
        icon: ["coding"],
        keywords: ["art", "tool", "coding", "generative", "tutorials"],
    },
    {
        name: "1018 Homepage Design Examples",
        url: "https://baymard.com/homepage-and-category-usability/benchmark/page-types/homepage",
        img: "hde",
        icon: ["coding"],
        keywords: ["coding", "design", "learn", "web"],
    },
    {
        name: "Devhints.io Rico's cheatsheets",
        url: "https://devhints.io/",
        img: "ric",
        icon: ["coding"],
        keywords: ["coding", "learn"],
    },
    {
        name: "The Million Dollar Homepage",
        url: "http://milliondollarhomepage.com",
        img: "mdp",
        icon: ["art", "photowarning", "nsfw"],
        keywords: ["fun", "weird", "web", "nsfw"],
    },
    {
        name: "Aesthetics Wiki",
        url: "https://aesthetics.fandom.com/wiki/List_of_Aesthetics",
        img: "aew",
        icon: ["art"],
        keywords: ["learn", "web", "wiki", "art"],
    },
    {
        name: "The Periodic Table of Storytelling",
        url: "https://jamesharris.design/periodic",
        img: "pts",
        icon: ["writing"],
        keywords: ["learn", "writing"],
    },
    {
        name: "Fractal Machine",
        url: "https://sciencevsmagic.net/fractal",
        img: "fra",
        icon: ["maths", "photowarning"],
        keywords: ["art", "games", "maths", "geometry", "fractals"],
    },
    {
        name: "Logic Grid",
        url: "https://sciencevsmagic.net/logicgrid",
        img: "log",
        icon: ["maths"],
        keywords: ["art", "maths", "geometry", "fractals", "grid"],
    },
    {
        name: "Tv Tropes",
        url: "https://tvtropes.org/pmwiki/pmwiki.php/Main/Tropes",
        img: "tvt",
        icon: ["writing"],
        keywords: ["art", "writing", "book", "wiki", "learn"],
    },
    {
        name: "Inkarnate",
        url: "https://inkarnate.com",
        img: "ink",
        icon: ["tool"],
        keywords: ["writing", "maps", "tool", "fun"],
    },
    {
        name: "Lifemap",
        url: "https://lifemap-ncbi.univ-lyon1.fr",
        img: "lml",
        icon: ["science"],
        keywords: ["learn", "life", "tree", "evolution", "maps"],
    },
    {
        name: "Itch.io",
        url: "https://itch.io",
        img: "itc",
        icon: ["various"],
        keywords: ["fun", "games", "coding", "art"],
    },
    {
        name: "Circos Table Viewer",
        url: "https://mk.bcgsc.ca/tableviewer",
        img: "ctv",
        icon: ["science"],
        keywords: ["learn", "medicine", "genetics"],
    },
    {
        name: "2b2t Maps",
        url: "https://map.daporkchop.net/#2021_256k_isometric/0/6/96/-656/0",
        img: "b2t",
        icon: ["games"],
        keywords: ["fun", "weird", "maps", "games", "web"],
    },
    {
        name: "LHC Page 1",
        url: "https://op-webtools.web.cern.ch/vistar/?usr=LHC1",
        img: "lhc",
        icon: ["science"],
        keywords: ["fun", "physics", "science"],
    },
    {
        name: "Human (GRCh38/hg38)",
        url: "https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr7%3A155799529%2D155812871&hgsid=346994980_E73Sa36VARAEPLasBPPOsvdRfbPS",
        img: "hum",
        icon: ["science"],
        keywords: ["learn", "medicine", "genetics"],
    },
    {
        name: "Science Vs Magic",
        url: "https://sciencevsmagic.net",
        img: "svm",
        icon: ["maths"],
        keywords: ["art", "maths", "geometry", "fractals", "learn"],
    },
    {
        name: "Tristan da Cunha",
        url: "https://tristandc.com/index.php",
        img: "tdc",
        icon: ["location"],
        keywords: ["learn", "location", "geography", "island", "sea"],
    },
    {
        name: "One Zoom Biota",
        url: "https://onezoom.org/linnean",
        img: "ozb",
        icon: ["science"],
        keywords: ["learn", "life", "tree", "evolution", "maps"],
    },
    {
        name: "Seismic Monitor",
        url: "https://ds.iris.edu/seismon/index.phtml",
        img: "sei",
        icon: ["science"],
        keywords: ["learn", "geography", "maps", "earthquake"],
    },
    {
        name: "The 2022 r/place Atlas",
        url: "https://2022.place-atlas.stefanocoding.me",
        img: "rpa",
        icon: ["art"],
        keywords: ["fun", "web", "maps", "art"],
    },
    {
        name: "Hashima Island",
        url: "https://hashima-island.co.uk",
        img: "has",
        icon: ["location"],
        keywords: ["fun", "weird", "island", "location"],
    },
    {
        name: "GifCities",
        url: "https://gifcities.org",
        img: "gif",
        icon: ["art"],
        keywords: ["fun", "art", "web"],
    },
    {
        name: "NaN.xyz",
        url: "https://nan.xyz",
        img: "nan",
        icon: ["art"],
        keywords: ["art", "web", "writing", "fonts"],
    },
    {
        name: "Amazondating.co",
        url: "https://amazondating.co",
        img: "amz",
        icon: ["art"],
        keywords: ["fun", "web", "weird"],
    },
    {
        name: "Ducksarethebest.com",
        url: "https://theuselessweb.site/ducksarethebest.com",
        img: "dab",
        icon: ["art", "photowarning"],
        keywords: ["fun", "web", "ducks", "photowarning"],
    },
    {
        name: "Cross Divisions",
        url: "https://crossdivisions.com",
        img: "crd",
        icon: ["art", "photowarning"],
        keywords: ["art", "web", "photowarning"],
    },
    {
        name: "The Scale of the Universe 2",
        url: "https://htwins.net/scale2",
        img: "sou",
        icon: ["science"],
        keywords: ["learn", "fun", "science", "space", "physics"],
    },
    {
        name: "Universal Paperclips",
        url: "https://decisionproblem.com/paperclips",
        img: "upp",
        icon: ["games"],
        keywords: ["game", "fun", "science", "space", "math"],
    },
    {
        name: "Radars-auto",
        url: "https://radars-auto.com",
        img: "raa",
        icon: ["tool"],
        keywords: ["tool", "fun", "radar", "map", "road", "control"],
    },
    {
        name: "Alexander Perrin",
        url: "https://alexanderperrin.com.au",
        img: "alx",
        icon: ["art"],
        keywords: ["art", "fun", "game"],
    },
    {
        name: "Short Trip",
        url: "https://alexanderperrin.com.au/paper/shorttrip",
        img: "sht",
        icon: ["games"],
        keywords: ["art", "fun", "game", "train", "cat"],
    },
    {
        name: "Aquarium.ru",
        url: "https://aquarium.ru/en",
        img: "aqa",
        icon: ["music", "photowarning"],
        keywords: ["art", "fun", "music", "unicorn", "licorne", "weird"],
    },
    {
        name: "Penderecki's Garden",
        url: "https://pendereckisgarden.pl/en",
        img: "peg",
        icon: ["art"],
        keywords: ["art", "music", "garden", "polish"],
    },
    {
        name: "The Dilla Dimension",
        url: "http://dilladimension.com",
        img: "tdd",
        icon: ["music", "photowarning"],
        keywords: ["art", "music", "garden", "fun", "donut", "weird"],
    },
    {
        name: "A Number From the Ghost",
        url: "https://anumberfromtheghost.com",
        img: "nfg",
        icon: ["music", "photowarning"],
        keywords: ["art", "music", "games", "fun", "weird"],
    },
    {
        name: "AnyDice",
        url: "https://anydice.com",
        img: "any",
        icon: ["tool"],
        keywords: ["tool", "dice", "math"],
    },
    {
        name: "Inkbots",
        url: "https://3dcomic.shop/inkbots/s01e01/index.html",
        img: "ikb",
        icon: ["art"],
        keywords: ["art", "3d", "comic", "ink"],
    },
    {
        name: "Gergely Gizella",
        url: "https://logartis.info",
        img: "ggg",
        icon: ["art"],
        keywords: ["art", "coding", "fly"],
    },
    {
        name: "LoL Champions Concepts",
        url: "https://kodpe.github.io/devoidlab/Frankz.html",
        img: "lol",
        icon: ["art"],
        keywords: ["art", "game", "kodp", "lol"],
    },
    {
        name: "My 3-lvl tin can",
        url: "https://kodpe.github.io/ipoi/img/sites/s42.png",
        img: "s42",
        icon: ["art"],
        keywords: ["art", "ascii", "kodp", "42", "school"],
    },
    {
        name: "Infinite Drum Machine",
        url: "https://experiments.withgoogle.com/ai/drum-machine/view",
        img: "idm",
        icon: ["tool"],
        keywords: ["art", "music", "google", "map"],
    },
    {
        name: "The Geocities Gallery",
        url: "https://geocities.restorativland.org",
        img: "gct",
        icon: ["various", "photowarning", "nsfw"],
        keywords: ["art", "fun", "web", "internet", "weird"],
    },
    {
        name: "Wheretaken",
        url: "https://wheretaken.teuteuf.fr",
        img: "wtk",
        icon: ["games"],
        keywords: ["fun", "game", "photo", "quiz", "countrie"],
    }

];

// 111, 112, 113 Mathieu
// 114, 115, 116 Clement
// 120, 121, 122 Laure
// todo rajouter idee de Laure