const lvlTitles = [
    "Newcomer",
    "Care Apprentice",
    "Paracetamol Carrier",
    "Heartbeat Listener",
    "Thermometer Handler",
    "First Aid Novice",
    "Basic Biology Buff",
    "Glove Rookie",
    "Simple Stitcher",
    "Stethoscope Student",
    "Symptom Spotter",
    "Injection Beginner",
    "Vital Signs Checker",
    "Syringe Starter",
    "Scalpel Trainee",
    "Cough Catcher",
    "Triage Trainee",
    "Bedside Beginner",
    "Antibiotics Amateur",
    "Checkup Champ",
    "Immune System Intern",
    "Clinic Climber",
    "Reflex Rookie",
    "Consultation Cadet",
    "Labcoat Learner",
    "Scrub Scout",
    "Pulse Professional",
    "Healing Helper",
    "Basic Anatomy Buff",
    "Health Hacker",
    "Prescription Partner",
    "Germ Guardian",
    "Ointment Officer",
    "White Coat Warrior",
    "Suture Scribe",
    "Bandage Boss",
    "X-Ray Explorer",
    "Blood Pressure Pro",
    "Immune Enthusiast",
    "Tendon Tinkerer",
    "Pathogen Pursuer",
    "Organ Analyst",
    "Health Hustler",
    "Flu Fighter",
    "Heart Rate Handler",
    "Bacteria Buster",
    "Gauze Genius",
    "Medical Maverick",
    "Vitals Virtuoso",
    "Diagnosis Dreamer",
    "Pathology Pupil",
    "Virus Vanquisher",
    "Allergy Analyzer",
    "Symptom Sleuth",
    "Therapy Thinker",
    "Hygiene Hero",
    "White Cell Warrior",
    "Cardio Captain",
    "Remedy Rookie",
    "Lab Results Reader",
    "Blood Bank Boss",
    "Infection Interceptor",
    "Antigen Analyst",
    "Medical Marvel",
    "Toxin Terminator",
    "Health Whiz",
    "Clinic Commander",
    "Nerve Navigator",
    "Cellular Savvy",
    "Bloodborne Buster",
    "Virus Virtuoso",
    "Wound Whisperer",
    "Injury Investigator",
    "Panacea Pioneer",
    "Health Hotshot",
    "Diagnostic Dazzler",
    "Immune Invoker",
    "Pathogen Prodigy",
    "Lifesaver Leader",
    "Prescription Prodigy",
    "Virus Vanquisher",
    "Pathology Phenom",
    "Recovery Rockstar",
    "Physician Healer",
    "Medical Mastermind",
    "Therapy Titan",
    "Molecular Maestro",
    "Big Blood Baron",
    "Immune Innovator",
    "Doctor Dynamo",
    "Symptom Grand Sage",
    "Healing Hero",
    "Medic Magician",
    "Anatomy Ace",
    "Health Honcho",
    "Critical Care Commander",
    "Medicine Maestro",
    "Grand Body Balancer",
    "Legendary Healer",
    "Ultimate Medic",
];