const motsRigolos = [
    "Arbre", 
    "Avion",
    "Atmosphère",
    "Acrobatie", 
    "Ambulance", 
    "Baignoire", 
    "Barbecue", 
    "Baleineau", 
    "Bidon d'essence", 
    "Caméscope", 
    "Cabestan", 
    "Cacahuète", 
    "Coquillage", 
    "Carton", 
    "Caillou", 
    "Chiffon", 
    "Dromadaire",
    "Drapeau",
    "Diabolo",
    "Dindon",
    "Débarbouillette",
    "Écureuil", 
    "Enclume", 
    "Extraterrestre", 
    "Emmental",
    "Excavatrice",
    "Forêt", 
    "Fromage",
    "Fourchette", 
    "Fantôme", 
    "Frisbee", 
    "Galaxie", 
    "Grenier", 
    "Guitare",
    "Horizontalité", 
    "Hibou", 
    "Hasard", 
    "Imprimante",
    "Igloo",
    "Interrupteur", 
    "Isomère",
    "Jambon",
    "Jeu",
    "Jerrican",
    "Joystick",
    "Kermesse",
    "Kiwi",
    "Klaxon",
    "Kayak",
    "Lutin",
    "Loup",
    "Lampion",
    "Lunettes",
    "Mer", 
    "Montagne", 
    "Marmite",
    "Mégaphone",
    "Moulin",
    "Nénuphar",
    "Noeud papillon",
    "Nuage",
    "Otarie",
    "Ours", 
    "Ombrage", 
    "Oreiller", 
    "Piraterie", 
    "Pamplemousse", 
    "Pain de campagne",
    "Papillon", 
    "Pelleteuse",
    "Quizz",
    "Quiche",
    "Quincaillerie",
    "Pomme", 
    "Pelle", 
    "Poulet", 
    "Rondin", 
    "Ramasse-miettes", 
    "Restaurant",
    "Salière",
    "Sifflet",
    "Station service", 
    "Tartine", 
    "Tapisserie", 
    "Tricot", 
    "Train", 
    "Tracteur", 
    "Ukulélé", 
    "Usine",
    "Ventouse",
    "Voie rapide",
    "Vampire", 
    "Wasabi",
    "Wapiti",
    "Wagon",
    "Xylophone",
    "Xylophagie",
    "Zigzag", 
    "Zébu", 
    "Zip", 
];

export function getTartinePensee() {
  return motsRigolos[Math.floor(Math.random() * motsRigolos.length)];
}

const etat = [
    "super", 
    "content", 
    "affamé", 
    "agité", 
    "apaisé", 
    "bien", 
    "hypnotique", 
    "joyeux", 
    "stressé", 
    "rêveur", 
    "anxieux", 
    "fatigué", 
    "malade", 
    "mourrant", 
];

export function getTartineEtat(max) {
  if (max >= 0 && max <= etat.length) {
    return etat[Math.floor(Math.random() * max)];
  }
  return etat[Math.floor(Math.random() * etat.length)];
}

const aime = [
    "pain", 
    "fromage" 
];

export function getTartineAime(id) {
  if (id % 2 === 0) {
    return aime[0];
  }
  return aime[1];
  // return aime[Math.floor(Math.random() * aime.length)];
}

export function randomNumberMinMax(min, max) {
 return Math.floor(Math.random() * max) + min;
}

const names = [
    "Gédéon",
    "Hildegarde",
    "Berthe",
    "Émeric",
    "Irma",
    "Eusèbe",
    "Odilon",
    "Aglaé",
    "Théodule",
    "Mélusine",
    "Achille",
    "Cunégonde",
    "Gervais",
    "Léocadie",
    "Gilbert",
    "Léonide",
    "Flavie",
    "Barnabé",
    "Rosalie",
    "Léon",
    "Yvonne",
    "Clovis",
    "Colette",
    "Albertine",
    "Séraphine",
    "Armand",
    "Théophane",
    "Léonora",
    "Fernand",
    "Nélie",
    "Alphonse",
    "Angélique",
    "Anselme",
    "Géraldine",
    "Hilaire",
    "Sévérine",
    "Godefroy",
    "Dorothée",
    "Eugénie",
    "Maurice",
    "Jacqueline",
    "Raymonde",
    "Auguste",
    "Hortense",
    "Prosper",
    "Madeleine",
    "Léandre",
    "Arlette",
    "Léopoldine",
    "Constant",
    "Andréa",
    "Léopold",
    "Virgile",
    "Pétronille",
    "Fernande",
    "Edmond",
    "Aldegonde",
    "Prosperine",
    "Martial",
    "Cécile",
    "Firmin",
    "Yvette",
    "Odette",
    "Paulin",
    "Clémentine",
    "Georges",
    "Georgette",
    "Eulalie",
    "Clotilde",
    "Cédric",
    "Gaspardine",
    "Anastasie",
    "Albéric",
    "Flore",
    "Cyprienne",
    "Hélène",
    "Rémi",
    "Mélanie",
    "Gervaise",
    "Faustin",
    "Perpétue",
    "Ferdinand",
    "Agnès",
    "Albert",
    "Delphine",
    "Dorothée",
    "Léonce",
    "Esmée",
    "Geoffroy",
    "Magdeleine",
    "Chantal",
    "Aimé",
    "Martine",
    "Léonide",
    "Clément",
    "Hermance",
    "Édith",
    "Marceline",
    "Armandine",
    "Virgile",
    "Nestor",
    "Bertillon",
    "Suzanne",
    "Amable",
    "Honoré",
    "Délia",
    "Philomène",
    "Frédéric",
    "Amélie",
    "Firmin",
    "Léontine",
    "Hyacinthe",
    "Remi",
    "Lucienne",
    "Désiré",
    "Léandre",
    "Marcelline",
    "Astérie",
    "Clotilde",
    "Sylvain",
    "Florestan",
    "Rosalie",
    "Arsène",
    "Blanchette",
    "Evariste",
    "Solange",
    "Romain",
    "Agnès",
    "Théodore",
    "Marius",
    "Apolline",
    "Gustave",
    "Bertine",
    "Octavie",
    "Constant",
    "Hippolyte",
    "Léocadie",
    "Julienne",
    "Prosper",
    "Léontine",
    "Théodore",
    "Paulin",
    "Théophanie",
    "Tanguy",
    "Mariette",
    "Gracieuse",
    "Anicet",
    "Clothilde",
    "Bernardine",
    "Casimir",
    "Eulalie",
    "Gervase",
    "Félicité",
    "Céline",
    "Magdelaine",
    "Edmée",
    "Virgilia",
    "Lucille",
    "Cyprien",
    "Anthime",
    "Faustine",
    "Rémi",
    "Léopold",
    "Georges",
    "Mauricette",
    "Aurélie",
    "Théodore",
    "Alix",
    "Edmondine",
    "Henriette",
    "Gervais",
    "Albertine",
    "Clément",
    "Éloïse",
    "Pénélope",
    "Georges",
    "Emile",
    "Goulven",
    "Basile",
    "Gisèle",
    "Léandre",
    "Suzanne",
    "Théophane",
    "Albert",
    "Eugénie",
    "Isidore",
    "Clarisse",
    "Euphémie",
    "Gustave",
    "Hortense",
    "Colombe",
    "Violette",
    "Félix",
    "Albertine",
    "Agathe",
    "Ursule",
    "Berthe",
    "Léocadie",
    "Léonore",
    "Médéric",
    "Jean-Baptiste",
    "Marie-Claire",
    "Pierre-Antoine",
    "Louis-Philippe",
    "Anne-Sophie",
    "Jean-Paul",
    "Sophie-Anne",
    "Henriette-Louise",
    "Claude-François",
    "Claire-Marie",
    "Jean-Charles",
    "Pierre-Louis",
    "Michel-André",
    "Jacques-Henri",
    "Marie-Laure",
    "Jean-Pierre",
    "Éric-Claude",
    "Isabelle-Margaux",
    "Marie-Noëlle",
    "Jean-Michel",
    "Pierre-Marie",
    "Anne-Marie",
    "Charles-Louis",
    "Marie-Josée",
    "Paul-Henri",
    "Bernard-François",
    "Pierre-Alexandre",
    "Marie-Emmanuelle",
    "Jean-François",
    "Louis-Antoine",
    "Marc-André",
    "Élisabeth-Jean",
    "René-Charles",
    "Alice-Sophie",
    "Pierre-Gilles",
    "Bernard-Michel",
    "Stéphanie-Anne",
    "Anne-Elisabeth",
    "Jean-Noël",
    "Henri-Gabriel",
    "Claire-Béatrice",
    "Louis-Marie",
    "Antoine-Gérard",
    "Jacqueline-Michel",
    "Jean-Luc",
    "Marie-Jeanne",
    "Pierre-Frédéric",
    "Sophie-Élisabeth",
    "Paul-Édouard",
    "Jacques-Pierre",
    "Alain-Michel",
    "Claude-Pierre",
    "Isabelle-Hélène",
    "Pierre-Félix",
    "Anne-Geneviève",
    "Éric-Jérôme",
    "Marie-Christine",
    "Jean-Pauline",
    "Louis-Gérard",
    "Claire-Lucie",
    "Jacques-René",
    "Michel-Vincent",
    "Marie-Rose",
    "Pierre-Benoît",
    "Anne-Renée",
    "Louis-Eugène",
    "Vincent-François",
    "Lucienne-Marie",
    "Charles-Gabriel",
    "Bernard-Jean",
    "René-Michel",
    "Jacques-Louis",
    "Pierre-Olivier",
    "Mathilde-Élise",
    "Lucie-Marie",
    "Jean-Marc",
    "Jacques-Daniel",
    "Édith-Claire",
    "Michel-Pierre",
    "Anne-Claire",
    "Georges-Jean",
    "Nicole-Marie",
    "Éric-Gérard",
    "Paul-Luc",
    "Catherine-Élisabeth",
    "Charles-Éric",
    "Jacques-Alexandre",
    "Jean-Marie",
    "Thierry-Philippe",
    "Agnès-Madeleine",
    "Pierre-Yves",
    "Jeanne-Françoise",
    "René-Joseph",
    "Sylvie-Marie",
    "Pierre-Arnaud",
    "Bernard-Édith",
    "Véronique-Anne",
    "Michel-Jacques",
    "Paul-Hubert",
    "Jean-Vincent",
    "Bjornulf",
    "Thorgrim",
    "Snorri",
    "Frekjord",
    "Astridnord",
    "Kveldulfr",
    "Gudmundar",
    "Haldor",
    "Grimlaug",
    "Sigrund",
    "Olafson",
    "Torbjorn",
    "Eirikson",
    "Runar",
    "Skaldun",
    "Ingmar",
    "Aelfric",
    "Sveinbjorn",
    "Tormod",
    "Valthor",
    "Ulfhild",
    "Ragnarok",
    "Edvardsson",
    "Hulda",
    "Njordar",
    "Frode",
    "Yngve",
    "Gudrunar",
    "Skogulf",
    "Valdrick",
    "Olavska",
    "Thrainar",
    "Ivarson",
    "Snille",
    "Brunnar",
    "Gudbjorn",
    "Fjellheim",
    "Sigvard",
    "Herjulf",
    "Skjoldr",
    "Aslaug",
    "Arvid",
    "Friggson",
    "Hrolf",
    "Eldrim",
    "Vagn",
    "Skade",
    "Gormund",
    "Einarsson",
    "Kettil",
    "Svartur",
    "Thjostolv",
    "Lagerulf",
    "Borger",
    "Grimulf",
    "Stenbjorn",
    "Eydis",
    "Olafsonn",
    "Bjornag",
    "Hrafn",
    "Ulvar",
    "Svantje",
    "Idunrik",
    "Fritjof",
    "Ormulf",
    "Balthild",
    "Rurik",
    "Knutvik",
    "Halvar",
    "Tormund",
    "Ulfsdottir",
    "Viggard",
    "Gudbrand",
    "Ragnhildr",
    "Snorvald",
    "Ingibjorg",
    "Asgerd",
    "Magnulf",
    "Thorkell",
    "Bardulf",
    "Gerdulf",
    "Arnbjorn",
    "Haraldson",
    "Torgeir",
    "Kista",
    "Sigridtor",
    "Vidskald",
    "Bjorgmund",
    "Thrainna",
    "Eirikdottir",
    "Valborg",
    "Olovsdottir",
    "Eskiln",
    "Ingmarna",
    "Frigga",
    "Bronnulf",
    "Fjorginn",
    "Torkel",
    "Bjarkk",
    "Torvild"
]

function getTartineName() {
  return names[Math.floor(Math.random() * names.length)];
}

export function createTartipod(tartipodId) {
  let tartipod = {
    id: tartipodId,
    name: getTartineName(),
    birthdate: new Date().getTime(),
    age: 0,
    status: getTartineEtat(10), // 10/14
    think: getTartinePensee(),
    favorite: getTartineAime(tartipodId),
    need: randomNumberMinMax(100, 1000),
    lvl: 1,
    xp: 0,
  }
  return tartipod;
}

export function getDaysBetween(timestamp1, timestamp2) {
    const diffInMs = Math.abs(timestamp1 - timestamp2);
    return Math.floor(diffInMs / (1000 * 60 * 60 * 24));
}

export function getHoursBetween(timestamp1, timestamp2) {
    const diffInMs = Math.abs(timestamp1 - timestamp2);
    return Math.floor(diffInMs / (1000 * 60 * 60));
}

export function getMinutesBetween(timestamp1, timestamp2) {
    const diffInMs = Math.abs(timestamp1 - timestamp2);
    return Math.floor(diffInMs / (1000 * 60));
}

function getDayOfYear(date = new Date()) {
    const startOfYear = new Date(date.getFullYear(), 0, 0); // 1er janvier
    const diff = date - startOfYear;
    const dayNumber = Math.floor(diff / (1000 * 60 * 60 * 24));
    return dayNumber;
}


export function getMoodOfDay(id, age, lvl) {
  const day = getDayOfYear();
  const seed = day + id + age + lvl;
  const newStateId = Math.floor(seed % (etat.length - 3)); // 10/14
  // console.log('new State id:', [newStateId], newStateId);
  return etat[newStateId];
}

export function computeTartipodFormuleNeed(tartipod) { // besoin par heure
  if (!tartipod)
    return null;
    return Math.floor(tartipod.need * (tartipod.lvl ** 8));
}

export function computeTartipodFormuleCost(tartipod) { // = cout du besion au prochain niveau
  if (!tartipod)
    return null;
  return Math.floor(tartipod.need * ((tartipod.lvl + 1) ** 8) + tartipod.need * tartipod.xp * 10);
}